//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AllocateQ3_ConsoleInteraction.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AllocateQ3_ConsoleInteraction.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to And on that farm he had a.
        /// </summary>
        public static string AndOnThatFarmHeHadA {
            get {
                return ResourceManager.GetString("AndOnThatFarmHeHadA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the name of animal {0}:.
        /// </summary>
        public static string AnimalName {
            get {
                return ResourceManager.GetString("AnimalName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the number of animals you want to add:.
        /// </summary>
        public static string AnimalNumberInput {
            get {
                return ResourceManager.GetString("AnimalNumberInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the sound of the {0}:.
        /// </summary>
        public static string AnimalSound {
            get {
                return ResourceManager.GetString("AnimalSound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to meow.
        /// </summary>
        public static string cat {
            get {
                return ResourceManager.GetString("cat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cluck.
        /// </summary>
        public static string chicken {
            get {
                return ResourceManager.GetString("chicken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cow.
        /// </summary>
        public static string cow {
            get {
                return ResourceManager.GetString("cow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dog.
        /// </summary>
        public static string dog {
            get {
                return ResourceManager.GetString("dog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to duck.
        /// </summary>
        public static string duck {
            get {
                return ResourceManager.GetString("duck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to enter Animals from input? Y/n.
        /// </summary>
        public static string EnterAnimalFromInput {
            get {
                return ResourceManager.GetString("EnterAnimalFromInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception: {0}.
        /// </summary>
        public static string Exception {
            get {
                return ResourceManager.GetString("Exception", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to choose Data driven or PolymorphismApproach for DataDriven type datadriven for Polymorphism type polymorphism?.
        /// </summary>
        public static string FirstInputQuestion {
            get {
                return ResourceManager.GetString("FirstInputQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to frog.
        /// </summary>
        public static string frog {
            get {
                return ResourceManager.GetString("frog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to goat.
        /// </summary>
        public static string goat {
            get {
                return ResourceManager.GetString("goat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Here a {0}, there a {0}, everywhere a {0}-{0}.
        /// </summary>
        public static string HereASoundThereASound {
            get {
                return ResourceManager.GetString("HereASoundThereASound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to neigh.
        /// </summary>
        public static string horse {
            get {
                return ResourceManager.GetString("horse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid input try again.
        /// </summary>
        public static string InvalidInput {
            get {
                return ResourceManager.GetString("InvalidInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do the next example.
        /// </summary>
        public static string NextExample {
            get {
                return ResourceManager.GetString("NextExample", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Old MacDonald had a farm, E-I-E-I-O.
        /// </summary>
        public static string OldMacDonaldHadAFarm {
            get {
                return ResourceManager.GetString("OldMacDonaldHadAFarm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pig.
        /// </summary>
        public static string pig {
            get {
                return ResourceManager.GetString("pig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sheep.
        /// </summary>
        public static string sheep {
            get {
                return ResourceManager.GetString("sheep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To stop the application type stop.
        /// </summary>
        public static string StopApplication {
            get {
                return ResourceManager.GetString("StopApplication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to With a {0}-{0} here and a {0}-{0} there.
        /// </summary>
        public static string WithASoundHereAndThere {
            get {
                return ResourceManager.GetString("WithASoundHereAndThere", resourceCulture);
            }
        }
    }
}
